### ISSUE TITLE
Broken Pattern Lab Lineages When Combined w/ Twig Namespaces

### ISSUE THREAD

**Issue by sghoweri** [EvanLovely/plugin-twig-namespaces#4]
I noticed that when we started to use your awesome plugin @EvanLovely, the fix I put in the main Pattern Lab PHP Core Repo stopped working (https://github.com/drupal-pattern-lab/patternlab-php-core/pull/5) and I started seeing dozens and dozens of "such and such is not a pattern" as a result.

For reference, I'm specifically using this to allow any pattern in Pattern Lab to be universally included via `{% Include "@bolt/button.twig" %}` to allow our monorepo pattern structure to be reorganized without blowing up a bunch of Include paths in the process (regardless on if, say, the button.twig file lives in the components vs atoms vs whatever folder.

Unfortunately this causes PL to get confused when matching up the universal path patterns are using via the "real" path based on the actual folder.

Thankfully I think I've got a fix I can drop in to the main PL PHP Core Repo which tries to match up the namespaced pattern with the ones internally registered in a Pattern Lineage can't be found. 

PR coming soon!

**Comment by EvanLovely** [comment]
Looks like this was fixed in https://github.com/pattern-lab/patternlab-php-core/pull/127
