### ISSUE TITLE
Missing dependencies basaltinc/twig-tools in EvanLovely/plugin-twig-namespaces

### ISSUE THREAD

**Issue by kpatidarsecben** [EvanLovely/plugin-twig-namespaces#7]
it looks like basaltinc/twig-tools is moved from github repositories (https://github.com/basaltinc/twig-tools/tree/master), due to that it is throwing error.

**Comment by normanlolx** [comment]
@EvanLovely – You know what happened here? Is everything okay?

Looks like all Basalt repos went private.

**Comment by EvanLovely** [comment]
@leymannx We were cleaning up some old stuff to tighten up security. We still want our Twig utilities & the Twig Renderer (used in both Pattern Lab & Knapsack) to be up, public, & supported. I pinged our engineer working on this, @freneticpixel to see what's going on.

**Comment by EvanLovely** [comment]
@kpatidarsecben @leymannx OK that repo is now public again!

**Comment by normanlolx** [comment]
Oh wow, thank you @EvanLovely!!

**Comment by EvanLovely** [comment]
Welcome!
